### ISSUE TITLE
能再改一下吗？

### ISSUE THREAD

**Issue by A125963** [city41/neospriteviewer#22]
改成像C工具一样

**Comment by A125963** [comment]
作者你好，能改成像C工具一样就好了，保存Spr，分割spr，能写入调色版。
![Screenshot_2024-07-07-05-10-38-832_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/36c1a64a-04c4-456d-9393-758d749ea84a)
![Screenshot_2024-07-07-05-10-48-250_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/f812a127-6e1e-4dfe-ae68-abcfe127628d)
![Screenshot_2024-07-07-05-10-50-704_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/a5986694-2d95-4fa1-bbca-d1e36b760419)
![Screenshot_2024-07-07-05-11-11-831_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/b172e5d5-6f7f-42cf-820f-47c33484a501)
![Screenshot_2024-07-07-05-11-13-764_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/2b6cdfbb-4eea-476b-96ce-5f67eeefb8e3)
![Screenshot_2024-07-07-05-11-21-460_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/becfeade-d9f4-4d4e-b2d1-736960fdd3b8)
![Screenshot_2024-07-07-05-11-19-588_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/093c2680-c865-426b-ac4a-37b6ea116511)

**Comment by city41** [comment]
Thanks for the request. But I am going to keep it as a website, which is more convenient and simpler.
