### ISSUE TITLE
作者好

### ISSUE THREAD

**Issue by A125963** [city41/neospriteviewer#25]
写成C工具开源就好了

**Comment by city41** [comment]
I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
> 我并不是将其作为 C 工具来编写的。如果您愿意，您可以 fork repi 并执行此操作。

嗯

**Comment by A125963** [comment]
还是不会编绎



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
用Node.js v22.7.0编绎吗？



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
我对这个图形工具非常感兴趣。我想把它编成一个应用添加调色板。作为图形移植工具。



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
哪部分是关键？源代码？



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
作者晚上好



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
希望作者出个编译教程



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
能转换spr就好了



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
导出CROM与spr



---- 回复的原邮件 ----
| 发件人 | Matt ***@***.***> |
| 日期 | 2024年07月21日 00:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [city41/neospriteviewer] 作者好 (Issue #25) |

I'm not writing this as a C tool. You can fork the repi and do it if you want.

**Comment by A125963** [comment]
作者你好，建设kawaks模拟器开源，谢谢了。
